In [1]:
import pandas as pd
import numpy as np

In [2]:
pd.__version__

'3.0.6'

In [3]:
df = pd.read_csv("car_fuel_efficiency_2026.csv")

In [4]:
df.head(2)

,model_year,origin,fuel_type,drivetrain,num_doors,engine_displacement,num_cylinders,horsepower,vehicle_weight,acceleration,fuel_efficiency_mpg
0,2006,Europe,Gasoline,Front-wheel drive,4,2180,6,243.0,3870,NaN,31.9
1,2008,Europe,Diesel,Front-wheel drive,4,2390,6,272.0,4210,NaN,31.3

In [5]:
df.index

RangeIndex(start=0, stop=10000, step=1)

In [7]:
df.nunique()

model_year              50
origin                   3
fuel_type                3
drivetrain               3
num_doors                4
engine_displacement    127
num_cylinders            5
horsepower             153
vehicle_weight         176
acceleration            93
fuel_efficiency_mpg    188
dtype: int64

In [8]:
df["fuel_type"].nunique()

3

In [16]:
df.isnull().sum()

model_year               0
origin                   0
fuel_type                0
drivetrain               0
num_doors                0
engine_displacement      0
num_cylinders            0
horsepower             877
vehicle_weight           0
acceleration           264
fuel_efficiency_mpg      0
dtype: int64

In [19]:
a = df[df["origin"] == "Asia"]
a["fuel_efficiency_mpg"].max()

np.float64(41.2)

In [25]:
horsepower = df["horsepower"]
old = horsepower.median()
mode = horsepower.mode().iloc[0]
horsepower = horsepower.fillna(mode)
new = horsepower.median()
old, new

(np.float64(254.0), np.float64(252.0))

In [27]:
a = df[df["origin"] == "Asia"]
a = a[["vehicle_weight","model_year"]]
a.head(7)

    vehicle_weight  model_year
2             4240        1996
6             4310        1992
8             4230        1997
10            4420        1978
15            3950        2007
16            4750        2021
22            4450        2019

In [40]:
X = a.head(7).values
X

array([[4240, 1996],
       [4310, 1992],
       [4230, 1997],
       [4420, 1978],
       [3950, 2007],
       [4750, 2021],
       [4450, 2019]])

In [41]:
XTX = X.T @ X
XTX

array([[131950500,  60750580],
       [ 60750580,  28041424]])

In [42]:
Inverse = np.linalg.inv(XTX)
Inverse

array([[ 2.96830537e-06, -6.43071025e-06],
       [-6.43071025e-06,  1.39675281e-05]])

In [43]:
y = np.array([1100, 1300, 800, 900, 1000, 1100, 1200])
y

array([1100, 1300,  800,  900, 1000, 1100, 1200])

In [45]:
w = Inverse @ X.T @ y
w

array([0.13644777, 0.2327492 ])

In [46]:
w.sum()

np.float64(0.36919696904925486)